#!/usr/bin/python

rule split_multiallelic:
    input:
        getStartVcf
    output:
        '{caller}_split_multiallelic_vcf_parts/{part}.vcf'
    params:
        module = 'module load vcflib/v1.0.0-rc0-331-g7e3d806'
    shell:
        '{params.module};vcfbreakmulti {input} > {output}'


rule left_align_trim:
    input:
        '{caller}_split_multiallelic_vcf_parts/{part}.vcf'
    output:
        '{caller}_left_align_trim/{part}.vcf'
    params:
        module = 'module load GATK/3.8-0',
        ref = config['REF']
    shell:
        '{params.module};GATK -m 4g LeftAlignAndTrimVariants -R {params.ref} --variant {input} -o {output}'

rule sort_min_rep_vcf:
    input:
        '{caller}_left_align_trim/{part}.vcf'
    output:
        '{caller}_sorted_min_rep_vcf_parts/{part}.vcf'
    params:
        module = 'module load IGVTools/2.3.98'
    shell:
        '{params.module};java -Xmx9g -Djava.awt.headless=true -jar $IGVTOOLS_JAR sort -m 100000 -t $TMPDIR {input} {output}'


