#!/usr/bin/python

rule select_giab_region:
    input:
        snp = 'SNP_parts/{part}.vcf',
        indel = 'INDEL_parts/{part}.vcf',
        giab_bed = getGiabBed
    output:
        snp = 'GiabRegion_SNP_parts_{giabSamp}/{part}.vcf',
        indel = 'GiabRegion_INDEL_parts_{giabSamp}/{part}.vcf'
    params:
        module = 'module load GATK/3.8-1',
        ref = config['REF']
    run:
        vcfKeepSamps = GiabSampleDict[wildcards.giabSamp]
        shell('{params.module};GATK -m 4g SelectVariants -R {params.ref} -V {input.snp} -L {input.giab_bed} -o {output.snp} -sn ' + ' -sn '.join(vcfKeepSamps))
        shell('{params.module};GATK -m 4g SelectVariants -R {params.ref} -V {input.indel} -L {input.giab_bed} -o {output.indel} -sn ' + ' -sn '.join(vcfKeepSamps))



rule select_giab_fp:
    input:
        snp = 'GiabRegion_SNP_parts_{giabSamp}/{part}.vcf',
        indel = 'GiabRegion_INDEL_parts_{giabSamp}/{part}.vcf',
        giab_vcf = getGiabVcf
    output:
        snp = 'GiabFP_SNP_parts_{giabSamp}/{part}.vcf',
        indel = 'GiabFP_INDEL_parts_{giabSamp}/{part}.vcf'
    params:
        module = 'module load GATK/3.8-1',
        ref = config['REF']
    run:
        shell('{params.module};GATK -m 4g SelectVariants -R {params.ref} -V {input.snp} --discordance {input.giab_vcf} -o {output.snp}'
        shell('{params.module};GATK -m 4g SelectVariants -R {params.ref} -V {input.indel} --discordance {input.giab_vcf} -o {output.indel}'


rule combine_parts_giab:
    input:
        sorted(expand('GiabFP_{{varType}}_parts_{{giabSamp}}/{part}.vcf', part = PARTS))
    output:
        'GiabFP_{varType}_combined_{giabSamp}/variants.vcf'
    run:
        with open(output[0], 'w') as out:
            with open(input[0]) as f:
                for line in f:
                    out.write(line)
            for partVcf in input[1:]:
                with open(partVcf) as f:
                    line = f.readline()
                    while line != '' and line[0] == '#':
                        line = f.readline()
                    while line != '':
                        out.write(line)
                        line = f.readline()


rule bgzip_combined_giab_vcf:
    input:
        'GiabFP_{varType}_combined_{giabSamp}/variants.vcf'
    output:
        'GiabFP_{varType}_combined_{giabSamp}/variants.vcf.gz'
    params:
        module = 'module load samtools/1.8'
    shell:
        '{params.module};bgzip {input}'

rule tabix_annotated_giab_vcf:
    input:
        'GiabFP_{varType}_combined_{giabSamp}/variants.vcf.gz'
    output:
        'GiabFP_{varType}_combined_{giabSamp}/variants.vcf.gz.tbi'
    params:
        module = 'module load samtools/1.8'
    shell:
        '{params.module};tabix -p vcf {input}'


##GATK CombineVariants makes multi-allelic variants, so I'm going to do something else.
rule merge_giab_vcfs:
    input:
        vcfs = expand('GiabFP_{{varType}}_combined_{giabSamp}/variants.vcf.gz', giabSamp = GiabSampleDict.keys()),
        tabix = expand('GiabFP_{{varType}}_combined_{giabSamp}/variants.vcf.gz.tbi', giabSamp = GiabSampleDict.keys())
    output:
        'GiabFP_{varType}_final/variants.vcf'
    run:
        vcfTabList = []
        for vcf in input.vcfs:
            vcfTabList.append(pysam.TabixFile(vcf))
        vcfChromDict = {}
        for vcf in vcfTabList:
            for chrom in vcf.contigs:
                if chrom.startswith('chr'):
                    check = chrom[3:]
                else:
                    check = chrom
                if check.isdigit():
                    vcfChromDict[int(check)] = chrom
                elif check == 'X':
                    vcfChromDict[23] = chrom
                elif check == 'Y':
                    vcfChromDict[24] = chrom
                elif check[0] == 'M':
                    vcfChromDict[25] = chrom
                else:
                    print('unrecognized chromosome ' + chrom)
                    sys.exit(1)
        with open(output[0], 'w') as out:
            for line in vcfTabList[0].header:
                if not line.startswith('#CHROM'):
                    out.write(line + '\n')
            line_list = line.split()
            out.write('\t'.join(line_list[:8]) + '\n')
            for num in sorted(vcfChromDict.keys()):
                chrom = vcfChromDict[num]
                posDict = {}
                for vcf in vcfTabList:
                    if chrom in vcf.contigs:
                        for line in vcf.fetch(chrom):
                            line_list = line.split()
                            (chrom, posStr, snp, ref, alt) = line_list[:5]
                            pos = int(posStr)
                            posDict[(pos, ref, alt)] = 1
                for (pos, ref, alt) in sorted(posDict.keys()):
                    out.write('\t'.join([chrom, str(pos), '.', ref, alt, '.', '.', '.']) + '\n')
        for vcf in vcfTabList:
            vcf.close()


rule merged_giab_tabix:
    input:
        'GiabFP_{varType}_final/variants.vcf'
    output:
        vcf = 'GiabFP_{varType}_final/variants.vcf.gz',
        tab = 'GiabFP_{varType}_final/variants.vcf.gz.tbi'
    params:
        module = 'module load samtools/1.8'
    shell:
        '{params.module};bgzip {input};tabix -p vcf {input}.gz'

